exports.setup = function (app) {

  const admin = require('./router/admins');
  const user = require('./router/users');
  const transporters = require('./router/transporters');
  const vehicles = require('./router/vehicles');
  const banks = require('./router/banks');
  const orders = require('./router/orders');
  const customers = require('./router/customer');
  const notification = require('./router/notification');
  const feedback = require('./router/feedback');
  const complains = require('./router/complains');
  const rates = require('./router/rates');
  const promo = require('./router/promo');
  const categories = require('./router/categories');
  const commodities = require('./router/commodities');
  const finance = require('./router/finance');
  const space = require('./router/space');
  const schedule = require('./router/schedules');
  const expenses = require('./router/expenses');
  const station = require('./router/stations');
  const modificationLogs = require('./router/modificationlogs');
  const cars = require('./router/cars');
  const support = require('./router/support');
  const stores = require('./router/stores');
  const timeslots = require('./router/timeslots');
  const statics = require('./router/statics');
  const clients = require('./router/clients');
  const news = require('./router/news');
  const jobs = require('./router/jobs');
  const policies = require('./router/policies');
  const contacts = require('./router/contacts');
  const prices = require('./router/prices');
  const earnings = require('./router/earnings');
  const timeSlices = require('./router/timeSlices');
  const promotions = require('./router/promotions');

  app.use("/api/v1/admin", admin);
  app.use("/api/v1/users", user);
  app.use("/api/v1/transporters", transporters);
  app.use("/api/v1/vehicles", vehicles);
  app.use("/api/v1/bank", banks);
  app.use("/api/v1/orders", orders);
  app.use("/api/v1/customers", customers);
  app.use("/api/v1/notifications", notification);
  app.use("/api/v1/feedback", feedback);
  app.use("/api/v1/complains", complains);
  app.use("/api/v1/rates", rates);
  app.use("/api/v1/promo", promo);
  app.use("/api/v1/categories", categories);
  app.use("/api/v1/commodities", commodities);
  app.use("/api/v1/finance", finance);
  app.use("/api/v1/space", space);
  app.use("/api/v1/expenses", expenses);
  app.use("/api/v1/stations", station);
  app.use("/api/v1/schedule", schedule);
  app.use("/api/v1/modificationlogs", modificationLogs);
  app.use("/api/v1/cars", cars);
  app.use("/api/v1/support", support);
  app.use("/api/v1/stores", stores);
  app.use("/api/v1/timeslots", timeslots);
  app.use("/api/v1/statics", statics);
  app.use("/api/v1/clients", clients);
  app.use("/api/v1/news", news);
  app.use("/api/v1/jobs", jobs);
  app.use("/api/v1/policies", policies);
  app.use("/api/v1/contacts", contacts);
  app.use("/api/v1/prices", prices);
  app.use("/api/v1/earnings", earnings);
  app.use("/api/v1/time-slices", timeSlices);
  app.use("/api/v1/promotions", promotions);
};

module.exports = exports;
